"""empty message

Revision ID: 930e01b2e1c0
Revises: 
Create Date: 2022-02-12 01:41:00.704687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930e01b2e1c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(precision=32, asdecimal=10), nullable=True),
    sa.Column('longitude', sa.Float(precision=32, asdecimal=10), nullable=True),
    sa.Column('description', sa.String(length=8000), nullable=True),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_table('signal',
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('signal_gid', sa.String(length=50), nullable=True),
    sa.Column('signal_name', sa.String(length=200), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.asset_id'], ),
    sa.PrimaryKeyConstraint('signal_id')
    )
    op.create_table('measurement',
    sa.Column('measurement_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('measurement_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signal.signal_id'], ),
    sa.PrimaryKeyConstraint('measurement_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurement')
    op.drop_table('signal')
    op.drop_table('asset')
    # ### end Alembic commands ###
